language: cpp
os: 
  - linux
compiler:
  - gcc
sudo: false
services: docker
env:
  global:
    - IMAGE_NAME=vasyahuyasa/remod

install:
  - sudo apt-get update
  - sudo apt-get install -y automake build-essential zlib1g-dev
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.15 bash)"
 
script:
  - cd src && make && make clean

before_deploy:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - cd ..
  - docker build --pull --cache-from "$IMAGE_NAME:latest" --tag "${IMAGE_NAME}:${TRAVIS_TAG}" .
  - docker tag "${IMAGE_NAME}:${TRAVIS_TAG}" "${IMAGE_NAME}:latest"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  on:
    tags: true